### ISSUE TITLE
Zach: can use && instead of returning null

### ISSUE THREAD

**Issue by juliebarwick** [INGENIOUS-LY/Project_Catwalk#43]
https://github.com/INGENIOUS-LY/Project_Catwalk/blob/844804d3b95f4d644c5c1f8b81769e2686dada7c/client/src/components/Related/Carousel.jsx#L111-L114

Since this is just returning null, another way to use conditional renderings is to use `&&`. For example: 

`{
        location < maxMove
          && <ForwardArrow onClick={this.rightMover} />
}`

**Comment by ZachariaLentz** [comment]
Issue resolved changed conditional to use '&&' instead of returning null in falsey case
