### ISSUE TITLE
Annie: prefer de-structuring props in the function definition parameter

### ISSUE THREAD

**Issue by juliebarwick** [INGENIOUS-LY/Project_Catwalk#45]
https://github.com/INGENIOUS-LY/Project_Catwalk/blob/844804d3b95f4d644c5c1f8b81769e2686dada7c/client/src/components/Reviews/breakdownProduct.jsx#L23

**Comment by ahjohnston** [comment]
Fixed! 
For stateful components, is there a better way to restructure that what I'm doing here?
![Screen Shot 2021-11-13 at 3 18 51 PM](https://user-images.githubusercontent.com/78059363/141657880-856abbc0-8eee-482d-9a8c-1cab1b6c02c9.png)

**Comment by juliebarwick** [comment]
That looks correct to me (except for the squiggles?).
