### ISSUE TITLE
Annie: use helper functions whenever possible to keep code clean

### ISSUE THREAD

**Issue by juliebarwick** [INGENIOUS-LY/Project_Catwalk#47]
https://github.com/INGENIOUS-LY/Project_Catwalk/blob/844804d3b95f4d644c5c1f8b81769e2686dada7c/client/src/components/Reviews/reviewTile.jsx#L10

This looks like a perfect example of code that could be extracted into a helper function that was kept elsewhere, like an utils file or folder.

Also good time to start removing those comments! 👍🏼

**Comment by ahjohnston** [comment]
I moved the date calculation to a helper function and scooted it out into a utils file
